### PR TITLE
Fix for WL message lock

### PR DESCRIPTION
**Pull request by yo2loj**
Fix for WL message send error with persistent lock

### CODE REVIEW

**Comment by maurizioandreotti** [comment]
sounds great!

I will do some tests later today before merging it into the master, maybe we can then push this as a new compiled beta on the group.io for larger testing

**Comment by yo2loj** [comment]
Before that, please let me do some code beautification. For now its ugly...

**Comment by maurizioandreotti** [comment]
Ok – still to do checks…

**Comment by yo2loj** [comment]
Ok, everything is in place and seems to be OK.

**Pull request merged**
